const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const localDateKey=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const entriesKey=d=>`void_${d||localDateKey()}`; const kegelKey=d=>`kegel_${d||localDateKey()}`; const buzz=()=>navigator.vibrate?.(10);
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function nowHM(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function setupSeg(id,attr,cb){const box=$(id);box?.querySelectorAll('button').forEach(b=>b.onclick=()=>{buzz();box.querySelectorAll('button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');cb?.(b)});return()=>box?.querySelector('.sel')?.dataset[attr]}
const getVol=setupSeg('#segVol','v'),getType=setupSeg('#segType','t');let hold=3,reps=10;setupSeg('#segKphase','hold',b=>{hold=+b.dataset.hold;reps=+b.dataset.reps;$('#kCount').textContent=`0 / ${reps}`});
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');scrollTo({top:0,behavior:'smooth'});if(b.dataset.tab==='history')renderHistory()});
$('#inTime').value=nowHM();$('#todayDate').textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});
function renderToday(){const data=load(entriesKey(),[]).sort((a,b)=>a.time.localeCompare(b.time));$('#stCount').textContent=data.length;$('#stPrec').textContent=data.filter(e=>e.type==='precaution').length;$('#stGap').textContent='–';if(data.length>1){const mins=data.map(e=>{const[h,m]=e.time.split(':').map(Number);return h*60+m});const avg=(mins.at(-1)-mins[0])/(mins.length-1);$('#stGap').textContent=`${Math.floor(avg/60)}h${String(Math.round(avg%60)).padStart(2,'0')}`}
$('#list').innerHTML=data.length?data.map((e,i)=>`<div class="entry"><span class="time">${e.time}</span><span class="meta"><span class="pill ${e.vol==='abondant'?'good':''}">${e.vol}</span>${e.type==='precaution'?'<span class="pill alert">précaution</span>':''}${e.drink?`<span class="pill muted">${e.drink}${e.amount?` · ${e.amount} ml`:''}</span>`:''}${e.note?`<span class="entry-note">${escapeHtml(e.note)}</span>`:''}</span><button class="del" data-i="${i}" aria-label="Supprimer">✕</button></div>`).join(''):'<div class="empty">Aucune entrée pour le moment.</div>';$$('.del').forEach(b=>b.onclick=()=>{const a=load(entriesKey(),[]).sort((x,y)=>x.time.localeCompare(y.time));a.splice(+b.dataset.i,1);save(entriesKey(),a);renderToday()})}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#addBtn').onclick=()=>{const arr=load(entriesKey(),[]);arr.push({time:$('#inTime').value||nowHM(),vol:getVol(),type:getType(),drink:$('#inDrink').value,amount:+$('#inAmount').value||0,note:$('#inNote').value.trim()});save(entriesKey(),arr);$('#inTime').value=nowHM();$('#inDrink').value='';$('#inAmount').value='';$('#inNote').value='';renderToday();toast('Entrée ajoutée')};
$('#resetDay').onclick=()=>{if(confirm("Effacer toutes les entrées d'aujourd'hui ?")){localStorage.removeItem(entriesKey());renderToday()}};
function allDays(n=14){const out=[];for(let i=n-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=localDateKey(d);out.push({key,date:d,data:load(entriesKey(key),[])})}return out}
function renderHistory(){const days=allDays(14),max=Math.max(1,...days.map(d=>d.data.length));$('#historyChart').innerHTML=days.map(d=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(4,d.data.length/max*120)}px" title="${d.data.length} entrées"></div><div class="bar-label">${d.date.toLocaleDateString('fr-FR',{weekday:'narrow'})}</div></div>`).join('');const total=days.reduce((s,d)=>s+d.data.length,0);$('#histTotal').textContent=total;$('#histAvg').textContent=(total/14).toFixed(1);$('#histPrec').textContent=days.reduce((s,d)=>s+d.data.filter(e=>e.type==='precaution').length,0)}
function exportData(){const payload={version:2,exportedAt:new Date().toISOString(),data:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith('void_')||k.startsWith('kegel_')||k.startsWith('plan_'))payload.data[k]=load(k,null)}const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`suivi-vesical-${localDateKey()}.json`;a.click();URL.revokeObjectURL(a.href)}
$('#exportBtn').onclick=exportData;$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());Object.entries(p.data||{}).forEach(([k,v])=>save(k,v));renderToday();renderHistory();toast('Sauvegarde restaurée')}catch{alert('Fichier invalide')}};
let running=false;$('#kStart').onclick=()=>{if(running)return;running=true;let rep=0,phase='hold',left=hold;const phaseEl=$('#kPhase'),count=$('#kCount'),ring=$('#kRing'),btn=$('#kStart');btn.disabled=true;btn.textContent='Séance en cours…';const tick=()=>{phaseEl.textContent=phase==='hold'?'CONTRACTE':'RELÂCHE';phaseEl.style.color=phase==='hold'?'var(--deep)':'var(--good)';ring.style.setProperty('--progress',`${((hold-left)/hold)*100}%`);ring.querySelector('span').textContent=left;if(left--<=0){buzz();if(phase==='hold'){phase='rest';left=hold}else{rep++;count.textContent=`${rep} / ${reps}`;if(rep>=reps){clearInterval(timer);running=false;btn.disabled=false;btn.textContent='Démarrer la séance';phaseEl.textContent='Série terminée ✓';ring.style.setProperty('--progress','100%');const n=load(kegelKey(),0)+1;save(kegelKey(),n);$('#kToday').textContent=n;toast('Série enregistrée');return}phase='hold';left=hold}}};tick();const timer=setInterval(tick,1000)};$('#kToday').textContent=load(kegelKey(),0);
const planItems={plan12:[['carnet','Tenir le carnet','Noter chaque passage et boisson'],['irritants','Réduire café / thé','Réduire progressivement et observer'],['kegel-appr','Kegel apprentissage','3 s / 3 s · 10 répétitions']],plan34:[['delai','Retarder progressivement','Commencer par 5 minutes'],['stop-prec','Limiter les passages préventifs','Attendre une vraie envie'],['kegel-renf','Kegel renforcement','5 s / 5 s · 10 répétitions']],planPerm:[['hydra','Hydratation régulière','Répartir sur la journée'],['stress','Relâcher les tensions','Respiration calme et abdomen détendu']]};function renderPlan(){const d=load(`plan_${localDateKey()}`,{});Object.entries(planItems).forEach(([box,items])=>{$('#'+box).innerHTML=items.map(([id,t,s])=>`<div class="task ${d[id]?'done':''}" data-id="${id}"><div class="check">${d[id]?'✓':''}</div><div><div class="task-title">${t}</div><small>${s}</small></div></div>`).join('')});$$('.task').forEach(el=>el.onclick=()=>{const x=load(`plan_${localDateKey()}`,{});x[el.dataset.id]=!x[el.dataset.id];save(`plan_${localDateKey()}`,x);renderPlan()})}renderPlan();
const currentTheme=load('theme','light');document.documentElement.dataset.theme=currentTheme;$('#themeBtn').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;save('theme',t)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderToday();renderHistory();