import{$,$$,localDateKey,entriesKey,kegelKey,planKey,load,save,getEntries,escapeHtml,minutes,formatGap,formatDate,uid}from'./data.js';
let selectedDate=localDateKey(),editContext=null,hold=3,reps=10,running=false;
export const buzz=()=>navigator.vibrate?.(10);
export function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1900)}
const nowHM=()=>{const d=new Date();return`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
function setupSeg(selector,attr,cb){const box=$(selector);box?.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{buzz();box.querySelectorAll('button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');cb?.(b)}));return()=>box?.querySelector('.sel')?.dataset[attr]}
const getVol=setupSeg('#segVol','v'),getType=setupSeg('#segType','t');
setupSeg('#segKphase','hold',b=>{hold=+b.dataset.hold;reps=+b.dataset.reps;$('#kCount').textContent=`Répétition 0 / ${reps}`});
function metrics(data){if(!data.length)return{count:0,prec:0,gap:NaN};const sorted=[...data].sort((a,b)=>a.time.localeCompare(b.time)),gaps=[];for(let i=1;i<sorted.length;i++){const g=minutes(sorted[i].time)-minutes(sorted[i-1].time);if(g>=0)gaps.push(g)}return{count:data.length,prec:data.filter(e=>e.type==='precaution').length,gap:gaps.length?gaps.reduce((a,b)=>a+b,0)/gaps.length:NaN}}
function entryHtml(e,date){return`<div class="entry"><span class="time">${escapeHtml(e.time)}</span><span class="meta"><span class="pill ${e.vol==='abondant'?'good':e.vol==='goutte'?'warm':''}">${e.vol==='goutte'?'faible':escapeHtml(e.vol)}</span>${e.type==='precaution'?'<span class="pill alert">précaution</span>':''}${e.drink?`<span class="pill muted">${escapeHtml(e.drink)}${e.amount?` · ${e.amount} ml`:''}</span>`:''}${e.urgency?`<span class="pill">urgence ${escapeHtml(e.urgency)}/5</span>`:''}${e.note?`<span class="entry-note">${escapeHtml(e.note)}</span>`:''}</span><span class="entry-actions"><button class="entry-btn edit-entry" data-date="${date}" data-id="${e.id}" aria-label="Modifier">✎</button><button class="entry-btn delete-entry danger-text" data-date="${date}" data-id="${e.id}" aria-label="Supprimer">✕</button></span></div>`}
function bindEntryActions(scope=document){scope.querySelectorAll('.edit-entry').forEach(b=>b.onclick=()=>openEdit(b.dataset.date,b.dataset.id));scope.querySelectorAll('.delete-entry').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.date,b.dataset.id))}
export function renderToday(){const date=localDateKey(),data=getEntries(date),m=metrics(data);$('#todayDate').textContent=formatDate(date,{weekday:'long',day:'numeric',month:'long'});$('#stCount').textContent=m.count;$('#stPrec').textContent=m.prec;$('#stGap').textContent=formatGap(m.gap);$('#list').innerHTML=data.length?data.map(e=>entryHtml(e,date)).join(''):'<div class="empty">Aucune entrée pour le moment.</div>';bindEntryActions($('#list'));$('#kToday').textContent=load(kegelKey(),0)}
export function renderSelectedDay(date=selectedDate){selectedDate=date;$('#historyDate').value=date;const data=getEntries(date),m=metrics(data);$('#historyDaySummary').innerHTML=`<span class="pill">${m.count} entrée${m.count>1?'s':''}</span><span class="pill muted">écart ${formatGap(m.gap)}</span><span class="pill ${m.prec?'alert':'good'}">${m.prec} précaution</span>`;$('#historyDayList').innerHTML=data.length?data.map(e=>entryHtml(e,date)).join(''):'<div class="empty">Aucune donnée pour cette journée.</div>';bindEntryActions($('#historyDayList'))}
function openEdit(date,id){const entry=getEntries(date).find(e=>e.id===id);if(!entry)return;editContext={date,id};$('#editTime').value=entry.time;$('#editDrink').value=entry.drink;$('#editAmount').value=entry.amount||'';$('#editUrgency').value=entry.urgency||'';$('#editVol').value=entry.vol;$('#editType').value=entry.type;$('#editNote').value=entry.note;$('#editDialog').showModal()}
function deleteEntry(date,id){if(!confirm('Supprimer cette entrée ?'))return;save(entriesKey(date),getEntries(date).filter(e=>e.id!==id));refreshAll();toast('Entrée supprimée')}
function refreshAll(){renderToday();renderSelectedDay(selectedDate);document.dispatchEvent(new CustomEvent('datachanged'))}
export function initTracker(){
 $('#inTime').value=nowHM();
 $('#addBtn').onclick=()=>{const arr=getEntries(localDateKey());arr.push({id:uid(),time:$('#inTime').value||nowHM(),vol:getVol()||'normal',type:getType()||'vraie',drink:$('#inDrink').value,amount:+$('#inAmount').value||0,urgency:$('#inUrgency').value,note:$('#inNote').value.trim()});save(entriesKey(),arr);$('#inTime').value=nowHM();$('#inDrink').value='';$('#inAmount').value='';$('#inUrgency').value='';$('#inNote').value='';refreshAll();toast('Entrée ajoutée')};
 $('#resetDay').onclick=()=>{if(confirm("Effacer toutes les entrées d'aujourd'hui ?")){localStorage.removeItem(entriesKey());refreshAll();toast('Journée effacée')}};
 $('#historyDate').value=selectedDate;$('#historyDate').onchange=e=>renderSelectedDay(e.target.value);$('#prevDayBtn').onclick=()=>shiftDay(-1);$('#nextDayBtn').onclick=()=>shiftDay(1);$('#goTodayBtn').onclick=()=>renderSelectedDay(localDateKey());
 $('#saveEditBtn').onclick=e=>{e.preventDefault();if(!editContext)return;const arr=getEntries(editContext.date),i=arr.findIndex(x=>x.id===editContext.id);if(i<0)return;arr[i]={...arr[i],time:$('#editTime').value,drink:$('#editDrink').value,amount:+$('#editAmount').value||0,urgency:$('#editUrgency').value,vol:$('#editVol').value,type:$('#editType').value,note:$('#editNote').value.trim()};save(entriesKey(editContext.date),arr);$('#editDialog').close();refreshAll();toast('Entrée modifiée')};
 $('#deleteEditBtn').onclick=()=>{if(editContext){$('#editDialog').close();deleteEntry(editContext.date,editContext.id)}};
 $('#kStart').onclick=runKegel;renderPlan();renderToday();renderSelectedDay();
}
function shiftDay(delta){const d=new Date(`${selectedDate}T12:00:00`);d.setDate(d.getDate()+delta);renderSelectedDay(localDateKey(d))}
function runKegel(){if(running)return;running=true;let rep=0,phase='hold',remaining=hold;const btn=$('#kStart'),phaseEl=$('#kPhase'),countEl=$('#kCount'),ring=$('#kRing'),seconds=$('#kSeconds');btn.disabled=true;btn.textContent='Séance en cours…';const update=()=>{phaseEl.textContent=phase==='hold'?'CONTRACTE':'RELÂCHE';phaseEl.style.color=phase==='hold'?'var(--deep)':'var(--good)';seconds.textContent=Math.max(remaining,0);ring.style.setProperty('--progress',`${((hold-remaining)/hold)*100}%`);if(remaining--<=0){buzz();if(phase==='hold'){phase='rest';remaining=hold}else{rep++;countEl.textContent=`Répétition ${rep} / ${reps}`;if(rep>=reps){clearInterval(timer);running=false;btn.disabled=false;btn.textContent='Démarrer la séance';phaseEl.textContent='Série terminée ✓';seconds.textContent='✓';ring.style.setProperty('--progress','100%');const n=load(kegelKey(),0)+1;save(kegelKey(),n);$('#kToday').textContent=n;toast('Série enregistrée');document.dispatchEvent(new CustomEvent('datachanged'));return}phase='hold';remaining=hold}}};update();const timer=setInterval(update,1000)}
const planItems={plan12:[['carnet','Tenir le carnet','Noter chaque passage et boisson'],['irritants','Réduire café / thé','Réduire progressivement et observer'],['kegel-appr','Kegel apprentissage','3 s / 3 s · 10 répétitions']],plan34:[['delai','Retarder progressivement','Commencer par 5 minutes'],['stop-prec','Limiter les passages préventifs','Attendre une vraie envie'],['kegel-renf','Kegel renforcement','5 s / 5 s · 10 répétitions']],planPerm:[['hydra','Hydratation régulière','Répartir sur la journée'],['stress','Relâcher les tensions','Respiration calme et abdomen détendu']]};
function renderPlan(){const state=load(planKey(),{});Object.entries(planItems).forEach(([box,items])=>{$('#'+box).innerHTML=items.map(([id,title,sub])=>`<div class="task ${state[id]?'done':''}" data-id="${id}"><div class="check">${state[id]?'✓':''}</div><div><div class="task-title">${title}</div><small>${sub}</small></div></div>`).join('')});$$('.task').forEach(el=>el.onclick=()=>{const x=load(planKey(),{});x[el.dataset.id]=!x[el.dataset.id];save(planKey(),x);renderPlan()})}